### ISSUE TITLE
Make chrome open with the batch file at a certain window size.

### ISSUE THREAD

**Issue by ArthurAllshire** [thedropbears/steamworks-dashboard#4]
We don't want to have to think; the drivers don't want to think about resizing the windows manually. Since we will know the screen size of the laptop, we should aim to have the chrome window open at a certain size (not maximised as the Driver station itself has to fit at the bottom of the window). There is code that _should_ allow us to do this at the moment in launch_ds.bat, but it doesn't work. This needs to be fixed.

**Comment by auscompgeek** [comment]
I suspect that the extra switches aren't actually being passed to the browser. You'll probably have to call Chrome directly rather than letting Windows use the file type association.
