### ISSUE TITLE
Adding MIT license

### ISSUE THREAD

**Issue by Oliver-Allshire** [thedropbears/steamworks-dashboard#7]

**Comment by Oliver-Allshire** [comment]
I agree to adding a MIT license.

**Comment by joelbryla** [comment]
I agree to adding a MIT license

**Comment by Matthew13479** [comment]
I agree to adding a MIT license

**Comment by fizzlebert** [comment]
I agree to adding the MIT license.

**Comment by ArthurAllshire** [comment]
I agree to adding an MIT license.

**Comment by auscompgeek** [comment]
As "MIT license" is ambiguous and could refer to various different licenses, I will assume that you are all referring to the MIT License as published by the OSI (i.e. the Expat License).

If this assumption is incorrect, please speak now or forever hold your peace.
